config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  get "contacts/new"
  post "contacts/create"
  get "/column", to: "home#column"
  get "/signup", to: "users#signup"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :laliga_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :bundesu_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :premier_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :serie_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :league_one_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :eredivisie_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :jupiler_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :premera_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :scotish_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :euro_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :nations_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :champions_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :europe_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :users
  resources :account_activations, only: [:edit]
  resources :relationships, only: [:create, :destroy]
  scope "/:locale" do
    resources :books
  end
  resource :profile, only: %i[show edit update]
  resources :users, only: [:index, :show]
  resources :microposts, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      フォームには<%=pluralize(@user.errors.count,"個のエラーがあります") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items,
                    params: { controller: :static_pages, action: :home } %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

<script type="text/javascript">
  $("#micropost_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#micropost_image").val("");
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
<section class="follow_info">
  <a href="<%= following_user_path(@user) %>">
    </section>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>