config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  get "contacts/new"
  post "contacts/create"
  get "/column", to: "home#column"
  get "/signup", to: "users#signup"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :laliga_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :bundesu_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :premier_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :serie_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :league_one_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :eredivisie_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :jupiler_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :premera_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :scotish_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :euro_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :nations_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :champions_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :europe_posts, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :users
  resources :account_activations, only: [:edit]
  resources :relationships, only: [:create, :destroy]
  scope "/:locale" do
    resources :books
  end
  resource :profile, only: %i[show edit update]
  resources :users, only: [:index, :show]
  resources :microposts, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/bundesu_post.rb
class BundesuPost < ApplicationRecord
  validates :title, presence: true, length: { maximum: 20 }
  validates :text, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user

  def correct_user(current_user)
    if id == current_user.id
      true
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/bundesu_posts_controller.rb
class BundesuPostsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:destroy]
  # 投稿一覧
  def index
    @bundesu_posts = BundesuPost.paginate(page: params[:page]).order(created_at: :desc)
  end

  #投稿作成画面
  def show
    @bundesu_post = current_user.bundesu_posts.build()
  end

  def new
    @bundesu_post = BundesuPost.new
  end

  #投稿内容保存
  def create
    @bundesu_post = current_user.bundesu_posts.build(post_params)
    if @bundesu_post.save
      redirect_to bundesu_posts_url
      flash[:success] = "投稿に成功しました"
    else
      flash.now[:danger] = "タイトルとコメント両方入力してください"
      render "bundesu_posts/new"
    end
  end

  def destroy
    @bundesu_post = BundesuPost.find(params[:id])
    @bundesu_post.destroy
    flash[:success] = "投稿を削除しました"
    redirect_back(fallback_location: "bundesu_post/index")
  end

  private

  def post_params
    params.require(:bundesu_post).permit(:title, :text, :image, :remove_image)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash.now[:danger] = "ログインして下さい"
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/bundesu_posts_helper.rb
module BundesuPostsHelper
end

app/views/bundesu_posts/index.html.erb
<%= stylesheet_link_tag "bundesu_index", media: 'all', 'data-turbolinks-track': 'reload' %>
<h1>ブンデスリーガ投稿一覧</h1>
<h2 class="bundesu_post_page">投稿ページはこちらへ<span class="new"><%= link_to "投稿ページへ", "/bundesu_posts/new" %></h2>
<div class="comments">
    <div class="comment">
        <% @bundesu_posts.each do |bundesu_post| %>
    </div>
    <div class="post">
        <div class="title">
            <p class="title">タイトル</p>
            <section class="title"><%= bundesu_post.title %></section>
        </div>
        <div class="comments">
            <p class="comments">コメント</p>
            <section class="comments"><%= bundesu_post.text %></section>
        </div>
        <div class="image">
            <section class="image"><%= image_tag bundesu_post.image.url if bundesu_post.image? %></section>
            <div class="post_destroy">
            <%= link_to("投稿削除", bundesu_post_path(bundesu_post), {method: :delete} ) %>
            </div>
            <p class="user_name">ユーザー名 <%= link_to(bundesu_post.user.name, user_path(bundesu_post.user_id)) %></p>
            <% end %>
        </div>
    </div>
</div>

app/views/bundesu_posts/new.html.erb
<%= stylesheet_link_tag "bundesu_new", media: 'all', 'data-turbolinks-track': 'reload' %>

<body>
    <h1 class="posts">ブンデスリーガ投稿</h1>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: @bundesu_post, local: true) do |f| %>
            <%= f.label :タイトル, class: "title" %>
            <%= f.text_field :title, class: "form-control" %>

            <%= f.label :コメント, class: "post_comment" %>
            <%= f.text_area :text, class: "form-control" %>

            <%= f.label :画像, class: "post_image" %>
            <%= f.file_field :image %>
            <%= f.submit "投稿", class: "btn btn-primary" %>


            <% end %>
        </div>
    </div>
</body>